"""
_constants.py - 兼容垫片

所有功能已迁移至 _patterns.py（正则模式）和 _utils.py（工具函数）。
"""

from ._patterns import (
    DATE_REGEX,
    DATE_TRAILING_RE,
    NEWS_URL_REGEX,
    BOILERPLATE_PATTERNS,
    CONTENT_EXTRACT_PATTERNS,
    HTML_EXTRACT_PATTERNS,
    MARKDOWN_LINK_RE,
    WHITESPACE_RE,
    # 以下供内部使用
    API_SCRIPT_PATTERN,
    _API_CONTENT_PATTERN,
    _AJAX_CONFIG_PATTERN,
    _AJAX_URL_PATTERN,
    _AJAX_TYPE_PATTERN,
    _AJAX_DATATYPE_PATTERN,
    _AJAX_JSONP_CALLBACK,
    _AJAX_PARAMS_PATTERN,
    _JQ_SIMPLE_PATTERN,
    _FETCH_PATTERN,
    _URL_VAR_PATTERN,
    _CNTV_API_PATTERN,
    _ATTR_REMOVE_RE,
    _ATTR_REMOVE_LINKLESS_RE,
    _ARTICLE_URL_RE,
    _SCRIPT_TAG_RE,
    _MARKDOWN_TITLE_URL_RE,
    _HTTP_PREFIX_RE,
    _HEADER_START_RE,
    _EXT_TRAILING_RE,
    _TITLE_PREFIX_RE,
    _LINE_SEP_RE,
    _LINE_FOREIGN_RE,
    _LINE_LINK_RE,
    _LINK_STRIP_RE,
    _LINE_CN_RE,
    _LINE_FOREIGN_COUNT_RE,
    _LINE_PUNCT_RE,
    _BP_DATE_RE,
    # title
    TIME_SUFFIX_RE,
    SOURCE_SUFFIX_RE,
    HEADER_RE,
    ISOLATED_BANG_RE,
    BRACKET_TRAILING_RE,
    # link
    PLAIN_URL_RE,
    BROKEN_LINK_RE,
    IMG_URL_RE,
    FILE_EXT_RE,
    # article content
    _ARTICLE_TITLE_RE,
    _TIME_CLASS_RE,
    _DETAIL_CONTENT_RE,
    _ARTICLE_CONTENT_RE,
    _CONTENT_CLASS_RE,
)
from ._utils import is_date_text

__all__ = [
    'DATE_REGEX', 'DATE_TRAILING_RE', 'NEWS_URL_REGEX',
    'BOILERPLATE_PATTERNS', 'CONTENT_EXTRACT_PATTERNS', 'HTML_EXTRACT_PATTERNS',
    'MARKDOWN_LINK_RE', 'WHITESPACE_RE', 'is_date_text',
    'TIME_SUFFIX_RE', 'SOURCE_SUFFIX_RE', 'HEADER_RE', 'ISOLATED_BANG_RE',
    'BRACKET_TRAILING_RE', 'PLAIN_URL_RE', 'BROKEN_LINK_RE', 'IMG_URL_RE', 'FILE_EXT_RE',
]